version: '3'

services:
  ui:
    image: food-ui
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    image: food-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
