export const actions = Object.freeze({
    CLEAR_PRODUCTS_ERROR: 'CLEAR_PRODUCTS_ERROR',
    FINISHED_FETCHING_PRODUCTS: 'FINISHED_FETCHING_PRODUCTS',
    NOTIFY_PRODUCTS_ERROR: 'NOTIFY_PRODUCTS_ERROR',
    RESET_PRODUCTS: 'RESET_PRODUCTS',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_PRODUCT_QUERY: 'SET_PRODUCT_QUERY',
    START_FETCHING_PRODUCTS: 'START_FETCHING_PRODUCTS',
});
