export const actions = Object.freeze({
    CLEAR_PRODUCTS_ERROR: 'CLEAR_PRODUCTS_ERROR',
    FINISHED_FETCHING_PRODUCTS: 'FINISHED_FETCHING_PRODUCTS',
    NOTIFY_PRODUCTS_ERROR: 'NOTIFY_PRODUCTS_ERROR',
    RESET_PRODUCTS: 'RESET_PRODUCTS',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_PRODUCT_QUERY: 'SET_PRODUCT_QUERY',
    START_FETCHING_PRODUCTS: 'START_FETCHING_PRODUCTS',
    SET_NUTRIENTS: 'SET_NUTRIENTS',
    START_FETCHING_NUTRIENTS: 'START_FETCHING_NUTRIENTS',
    CLEAR_NUTRIENTS_ERROR: 'CLEAR_NUTRIENTS_ERROR',
    RESET_NUTRIENTS: 'RESET_NUTRIENTS',
    NOTIFY_NUTRIENTS_ERROR: 'NOTIFY_NUTRIENTS_ERROR',
    FINISHED_FETCHING_NUTRIENTS: 'FINISHED_FETCHING_NUTRIENTS',
    SET_NUTRIENT_QUERY: 'SET_NUTRIENT_QUERY'
});
